name = "Anchor"
license = "MIT"
licenselink = "https://github.com/jadojodo/hxl-theme/blob/master/LICENSE"
description = "A theme."
homepage = "https://github.com/jadojodo/hxl-theme"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Jordan \"Jado\" Finnigan"
  homepage = "https://hxl.io"